name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: actions/setup-java@v1
    - run: |
        set -e
        node -v
        npm -v
        java --version
